2014-10-19 17:36:25 ERROR DBTaskManager                  - 已经创建人任务时间失败
java.lang.NumberFormatException: For input string: "NEWQYKB"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:449)
	at java.lang.Integer.<init>(Integer.java:660)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1149)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 17:52:39 ERROR DBTaskManager                  - 创建任务时间
java.lang.ArrayIndexOutOfBoundsException: 2014
	at java.util.Calendar.internalGet(Calendar.java:1145)
	at java.util.Calendar.get(Calendar.java:1132)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1107)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1152)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 17:54:06 ERROR DBTaskManager                  - 创建任务时间
java.lang.ArrayIndexOutOfBoundsException: 2014
	at java.util.Calendar.internalGet(Calendar.java:1145)
	at java.util.Calendar.get(Calendar.java:1132)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1107)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1152)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 17:55:30 ERROR DBTaskManager                  - 创建任务时间
java.lang.ArrayIndexOutOfBoundsException: 2014
	at java.util.Calendar.internalGet(Calendar.java:1145)
	at java.util.Calendar.get(Calendar.java:1132)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1107)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1152)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 18:10:48 ERROR DBTaskManager                  - 创建任务时间失败
net.sf.hibernate.HibernateException: Session is closed
	at net.sf.hibernate.impl.SessionImpl.connection(SessionImpl.java:3250)
	at net.sf.hibernate.transaction.JDBCTransaction.rollback(JDBCTransaction.java:86)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1162)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 18:10:48 ERROR DBTaskManager                  - 创建任务时间失败
net.sf.hibernate.HibernateException: Session is closed
	at net.sf.hibernate.impl.SessionImpl.connection(SessionImpl.java:3250)
	at net.sf.hibernate.impl.BatcherImpl.prepareStatement(BatcherImpl.java:61)
	at net.sf.hibernate.impl.BatcherImpl.prepareStatement(BatcherImpl.java:56)
	at net.sf.hibernate.impl.BatcherImpl.prepareBatchStatement(BatcherImpl.java:109)
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:460)
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:442)
	at net.sf.hibernate.impl.ScheduledInsertion.execute(ScheduledInsertion.java:29)
	at net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2382)
	at net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2335)
	at net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2204)
	at net.sf.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:61)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1155)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 18:13:46 ERROR DBTaskManager                  - 创建任务时间失败
net.sf.hibernate.TransactionException: Rollback failed with SQL exception: 
	at net.sf.hibernate.transaction.JDBCTransaction.rollback(JDBCTransaction.java:91)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1161)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.sql.SQLException: You can't operate on a closed connection!!!
	at com.mchange.v2.c3p0.impl.C3P0PooledConnection$ProxyConnectionInvocationHandler.invoke(C3P0PooledConnection.java:715)
	at com.mchange.v2.c3p0.impl.$Proxy22.rollback(Unknown Source)
	at net.sf.hibernate.transaction.JDBCTransaction.rollback(JDBCTransaction.java:86)
	... 17 more
2014-10-19 18:13:46 ERROR DBTaskManager                  - 创建任务时间失败
net.sf.hibernate.JDBCException: could not insert: [cn.com.youtong.apollo.task.db.form.TaskTimeForm#100]
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:478)
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:442)
	at net.sf.hibernate.impl.ScheduledInsertion.execute(ScheduledInsertion.java:29)
	at net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2382)
	at net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2335)
	at net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2204)
	at net.sf.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:61)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1153)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.sql.SQLException: You can't operate on a closed connection!!!
	at com.mchange.v2.c3p0.impl.C3P0PooledConnection$ProxyConnectionInvocationHandler.invoke(C3P0PooledConnection.java:715)
	at com.mchange.v2.c3p0.impl.$Proxy22.prepareStatement(Unknown Source)
	at net.sf.hibernate.impl.BatcherImpl.getPreparedStatement(BatcherImpl.java:249)
	at net.sf.hibernate.impl.BatcherImpl.prepareStatement(BatcherImpl.java:61)
	at net.sf.hibernate.impl.BatcherImpl.prepareStatement(BatcherImpl.java:56)
	at net.sf.hibernate.impl.BatcherImpl.prepareBatchStatement(BatcherImpl.java:109)
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:460)
	... 23 more
2014-10-19 18:13:48 ERROR DBTaskManager                  - 创建任务时间失败
net.sf.hibernate.TransactionException: Rollback failed with SQL exception: 
	at net.sf.hibernate.transaction.JDBCTransaction.rollback(JDBCTransaction.java:91)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1161)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.sql.SQLException: You can't operate on a closed connection!!!
	at com.mchange.v2.c3p0.impl.C3P0PooledConnection$ProxyConnectionInvocationHandler.invoke(C3P0PooledConnection.java:715)
	at com.mchange.v2.c3p0.impl.$Proxy22.rollback(Unknown Source)
	at net.sf.hibernate.transaction.JDBCTransaction.rollback(JDBCTransaction.java:86)
	... 17 more
2014-10-19 18:13:48 ERROR DBTaskManager                  - 创建任务时间失败
net.sf.hibernate.JDBCException: could not insert: [cn.com.youtong.apollo.task.db.form.TaskTimeForm#100]
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:478)
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:442)
	at net.sf.hibernate.impl.ScheduledInsertion.execute(ScheduledInsertion.java:29)
	at net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2382)
	at net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2335)
	at net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2204)
	at net.sf.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:61)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1153)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.sql.SQLException: You can't operate on a closed connection!!!
	at com.mchange.v2.c3p0.impl.C3P0PooledConnection$ProxyConnectionInvocationHandler.invoke(C3P0PooledConnection.java:715)
	at com.mchange.v2.c3p0.impl.$Proxy22.prepareStatement(Unknown Source)
	at net.sf.hibernate.impl.BatcherImpl.getPreparedStatement(BatcherImpl.java:249)
	at net.sf.hibernate.impl.BatcherImpl.prepareStatement(BatcherImpl.java:61)
	at net.sf.hibernate.impl.BatcherImpl.prepareStatement(BatcherImpl.java:56)
	at net.sf.hibernate.impl.BatcherImpl.prepareBatchStatement(BatcherImpl.java:109)
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:460)
	... 23 more
2014-10-19 18:18:19 ERROR DBTaskManager                  - 创建任务时间
net.sf.hibernate.TransactionException: Begin failed with SQL exception: 
	at net.sf.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:49)
	at net.sf.hibernate.transaction.JDBCTransactionFactory.beginTransaction(JDBCTransactionFactory.java:19)
	at net.sf.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:2195)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1105)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1154)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.sql.SQLException: You can't operate on a closed connection!!!
	at com.mchange.v2.c3p0.impl.C3P0PooledConnection$ProxyConnectionInvocationHandler.invoke(C3P0PooledConnection.java:715)
	at com.mchange.v2.c3p0.impl.$Proxy22.getAutoCommit(Unknown Source)
	at net.sf.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:40)
	... 20 more
2014-10-19 18:21:00 ERROR DBTaskManager                  - 创建任务时间
net.sf.hibernate.JDBCException: could not insert: [cn.com.youtong.apollo.task.db.form.TaskTimeForm#100]
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:478)
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:442)
	at net.sf.hibernate.impl.ScheduledInsertion.execute(ScheduledInsertion.java:29)
	at net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2382)
	at net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2335)
	at net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2204)
	at net.sf.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:61)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1121)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1149)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Column 'taskID' cannot be null
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1169)
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:693)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1404)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1318)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1303)
	at com.mchange.v2.sql.filter.FilterPreparedStatement.executeUpdate(FilterPreparedStatement.java:71)
	at net.sf.hibernate.impl.NonBatchingBatcher.addToBatch(NonBatchingBatcher.java:22)
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:468)
	... 24 more
2014-10-19 18:21:34 ERROR DBTaskManager                  - 创建任务时间
net.sf.hibernate.JDBCException: could not insert: [cn.com.youtong.apollo.task.db.form.TaskTimeForm#100]
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:478)
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:442)
	at net.sf.hibernate.impl.ScheduledInsertion.execute(ScheduledInsertion.java:29)
	at net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2382)
	at net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2335)
	at net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2204)
	at net.sf.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:61)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1121)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1149)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Column 'taskID' cannot be null
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1169)
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:693)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1404)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1318)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1303)
	at com.mchange.v2.sql.filter.FilterPreparedStatement.executeUpdate(FilterPreparedStatement.java:71)
	at net.sf.hibernate.impl.NonBatchingBatcher.addToBatch(NonBatchingBatcher.java:22)
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:468)
	... 24 more
2014-10-19 18:56:01 ERROR DBTaskManager                  - 创建任务时间
net.sf.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save(): cn.com.youtong.apollo.task.db.form.TaskTimeForm
	at net.sf.hibernate.id.Assigned.generate(Assigned.java:26)
	at net.sf.hibernate.impl.SessionImpl.saveWithGeneratedIdentifier(SessionImpl.java:747)
	at net.sf.hibernate.impl.SessionImpl.save(SessionImpl.java:720)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1126)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1155)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 18:56:32 ERROR DBTaskManager                  - 创建任务时间
net.sf.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save(): cn.com.youtong.apollo.task.db.form.TaskTimeForm
	at net.sf.hibernate.id.Assigned.generate(Assigned.java:26)
	at net.sf.hibernate.impl.SessionImpl.saveWithGeneratedIdentifier(SessionImpl.java:747)
	at net.sf.hibernate.impl.SessionImpl.save(SessionImpl.java:720)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1126)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1155)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 18:56:32 ERROR DBTaskManager                  - 创建任务时间
net.sf.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save(): cn.com.youtong.apollo.task.db.form.TaskTimeForm
	at net.sf.hibernate.id.Assigned.generate(Assigned.java:26)
	at net.sf.hibernate.impl.SessionImpl.saveWithGeneratedIdentifier(SessionImpl.java:747)
	at net.sf.hibernate.impl.SessionImpl.save(SessionImpl.java:720)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1126)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1155)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 18:56:33 ERROR DBTaskManager                  - 创建任务时间
net.sf.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save(): cn.com.youtong.apollo.task.db.form.TaskTimeForm
	at net.sf.hibernate.id.Assigned.generate(Assigned.java:26)
	at net.sf.hibernate.impl.SessionImpl.saveWithGeneratedIdentifier(SessionImpl.java:747)
	at net.sf.hibernate.impl.SessionImpl.save(SessionImpl.java:720)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1126)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1155)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 18:56:33 ERROR DBTaskManager                  - 创建任务时间
net.sf.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save(): cn.com.youtong.apollo.task.db.form.TaskTimeForm
	at net.sf.hibernate.id.Assigned.generate(Assigned.java:26)
	at net.sf.hibernate.impl.SessionImpl.saveWithGeneratedIdentifier(SessionImpl.java:747)
	at net.sf.hibernate.impl.SessionImpl.save(SessionImpl.java:720)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1126)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1155)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 18:56:34 ERROR DBTaskManager                  - 创建任务时间
net.sf.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save(): cn.com.youtong.apollo.task.db.form.TaskTimeForm
	at net.sf.hibernate.id.Assigned.generate(Assigned.java:26)
	at net.sf.hibernate.impl.SessionImpl.saveWithGeneratedIdentifier(SessionImpl.java:747)
	at net.sf.hibernate.impl.SessionImpl.save(SessionImpl.java:720)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1126)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1155)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 18:56:34 ERROR DBTaskManager                  - 创建任务时间
net.sf.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save(): cn.com.youtong.apollo.task.db.form.TaskTimeForm
	at net.sf.hibernate.id.Assigned.generate(Assigned.java:26)
	at net.sf.hibernate.impl.SessionImpl.saveWithGeneratedIdentifier(SessionImpl.java:747)
	at net.sf.hibernate.impl.SessionImpl.save(SessionImpl.java:720)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1126)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1155)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 19:02:11 ERROR DBTaskManager                  - 创建任务时间
net.sf.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save(): cn.com.youtong.apollo.task.db.form.TaskTimeForm
	at net.sf.hibernate.id.Assigned.generate(Assigned.java:26)
	at net.sf.hibernate.impl.SessionImpl.saveWithGeneratedIdentifier(SessionImpl.java:747)
	at net.sf.hibernate.impl.SessionImpl.save(SessionImpl.java:720)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1127)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1156)
	at cn.com.youtong.apollo.servlet.ModelServlet.showUnitTreeByNameOrCode(ModelServlet.java:408)
	at cn.com.youtong.apollo.servlet.ModelServlet.perform(ModelServlet.java:2296)
	at cn.com.youtong.apollo.servlet.RootServlet.service(RootServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:864)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1665)
	at java.lang.Thread.run(Thread.java:662)
2014-10-19 19:15:04 ERROR DBTaskManager                  - 创建任务时间
net.sf.hibernate.JDBCException: could not insert: [cn.com.youtong.apollo.task.db.form.TaskTimeForm#2015]
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:478)
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:442)
	at net.sf.hibernate.impl.ScheduledInsertion.execute(ScheduledInsertion.java:29)
	at net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2382)
	at net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2335)
	at net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2204)
	at net.sf.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:61)
	at cn.com.youtong.apollo.task.db.DBTaskManager.createTaskTime(DBTaskManager.java:1128)
	at cn.com.youtong.apollo.task.db.DBTaskManager.publishTaskTime(DBTaskManager.java:1156)
	at cn.com.youtong.apollo.timer.CreateTimeFieldTask.run(CreateTimeFieldTask.java:35)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
Caused by: com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry '2015' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1169)
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:693)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1404)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1318)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1303)
	at com.mchange.v2.sql.filter.FilterPreparedStatement.executeUpdate(FilterPreparedStatement.java:71)
	at net.sf.hibernate.impl.NonBatchingBatcher.addToBatch(NonBatchingBatcher.java:22)
	at net.sf.hibernate.persister.EntityPersister.insert(EntityPersister.java:468)
	... 11 more
